name: Test Pipeline

on: [push]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello, GitHub Actions is working!"

      - name: Show current folder
        run: pwd

      - name: List files
        run: ls -la
